name: Build and publish Flatpak using YAML manifest

on:
  schedule:
    - cron: '0 0 * * *' # Ежедневный запуск
  workflow_dispatch: # Ручной запуск

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up working directory
        run: |
          mkdir -p /workspace
          cd /workspace

      - name: Install dependencies
        run: |
          apk add --no-cache jq python3 py3-pip
          pip3 install flatpak-external-data-exporter

      - name: Generate manifest from YML
        run: |
          cp ../org.murglar.Murglar.yml /workspace/org.murglar.Murglar.builder
          cd /workspace
          flatpak-external-data-exporter --output-json org.murglar.Murglar.json org.murglar.Murglar.builder

      - name: Add JBR 21 extension
        run: |
          cat > /workspace/jbr-extension.json <<- 'EOL'
            {
              "add-extensions": {
                "org.jetbrains.jbr.vanilla": {
                  "directory": "jbr",
                  "version": "21",
                  "required": true,
                  "autodelete": false
                }
              }
            }
            EOL
          jq -s '.[0] * .[1]' org.murglar.Murglar.json jbr-extension.json > final.json && mv final.json org.murglar.Murglar.json

      - name: Copy run script
        run: |
          cp ../run.sh /workspace/run.sh

      - name: Install Flathub repo
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo 

      - name: Build application with flatpak-builder-action
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest: /workspace/org.murglar.Murglar.json
          export-path: /workspace/repo
          bundle: Murglar.flatpak

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Murglar.flatpak
          path: Murglar.flatpak

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: "Murglar Flatpak v${{ env.LATEST_TAG }}"
          tag: "${{ env.LATEST_TAG }}"
          generateReleaseNotes: true
          artifacts: "Murglar.flatpak"
          overwrite: true
